repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3.10
        args: ['--skip-string-normalization', '--line-length', '120']
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0  # Use the latest version of flake8
    hooks:
      - id: flake8
  - repo: https://github.com/myint/autoflake
    rev: v2.0.0  # Use the latest version of autoflake
    hooks:
      - id: autoflake
        args: ['--remove-all-unused-imports', '--remove-unused-variables', '--in-place', '--recursive']
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0  # Use the latest version of isort
    hooks:
      - id: isort
        args: ['--profile', 'black']  # Assuming you want to use the black profile for isort
